# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
